/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthTeacherRouteRouteImport } from './routes/_auth/teacher/route'
import { Route as AuthLearnRouteRouteImport } from './routes/_auth/learn/route'
import { Route as AuthAdminRouteRouteImport } from './routes/_auth/admin/route'
import { Route as AuthTeacherIndexRouteImport } from './routes/_auth/teacher/index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as AuthLearnSelectTaskRouteImport } from './routes/_auth/learn/select-task'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTeacherRouteRoute = AuthTeacherRouteRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLearnRouteRoute = AuthLearnRouteRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminRouteRoute = AuthAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTeacherIndexRoute = AuthTeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthTeacherRouteRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthLearnSelectTaskRoute = AuthLearnSelectTaskRouteImport.update({
  id: '/select-task',
  path: '/select-task',
  getParentRoute: () => AuthLearnRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/admin': typeof AuthAdminRouteRouteWithChildren
  '/learn': typeof AuthLearnRouteRouteWithChildren
  '/teacher': typeof AuthTeacherRouteRouteWithChildren
  '/learn/select-task': typeof AuthLearnSelectTaskRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/teacher/': typeof AuthTeacherIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/learn': typeof AuthLearnRouteRouteWithChildren
  '/learn/select-task': typeof AuthLearnSelectTaskRoute
  '/admin': typeof AuthAdminIndexRoute
  '/teacher': typeof AuthTeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/admin': typeof AuthAdminRouteRouteWithChildren
  '/_auth/learn': typeof AuthLearnRouteRouteWithChildren
  '/_auth/teacher': typeof AuthTeacherRouteRouteWithChildren
  '/_auth/learn/select-task': typeof AuthLearnSelectTaskRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/teacher/': typeof AuthTeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/admin'
    | '/learn'
    | '/teacher'
    | '/learn/select-task'
    | '/admin/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/learn' | '/learn/select-task' | '/admin' | '/teacher'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/admin'
    | '/_auth/learn'
    | '/_auth/teacher'
    | '/_auth/learn/select-task'
    | '/_auth/admin/'
    | '/_auth/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/teacher': {
      id: '/_auth/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthTeacherRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/learn': {
      id: '/_auth/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthLearnRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/teacher/': {
      id: '/_auth/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthTeacherIndexRouteImport
      parentRoute: typeof AuthTeacherRouteRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/learn/select-task': {
      id: '/_auth/learn/select-task'
      path: '/select-task'
      fullPath: '/learn/select-task'
      preLoaderRoute: typeof AuthLearnSelectTaskRouteImport
      parentRoute: typeof AuthLearnRouteRoute
    }
  }
}

interface AuthAdminRouteRouteChildren {
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

const AuthAdminRouteRouteChildren: AuthAdminRouteRouteChildren = {
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}

const AuthAdminRouteRouteWithChildren = AuthAdminRouteRoute._addFileChildren(
  AuthAdminRouteRouteChildren,
)

interface AuthLearnRouteRouteChildren {
  AuthLearnSelectTaskRoute: typeof AuthLearnSelectTaskRoute
}

const AuthLearnRouteRouteChildren: AuthLearnRouteRouteChildren = {
  AuthLearnSelectTaskRoute: AuthLearnSelectTaskRoute,
}

const AuthLearnRouteRouteWithChildren = AuthLearnRouteRoute._addFileChildren(
  AuthLearnRouteRouteChildren,
)

interface AuthTeacherRouteRouteChildren {
  AuthTeacherIndexRoute: typeof AuthTeacherIndexRoute
}

const AuthTeacherRouteRouteChildren: AuthTeacherRouteRouteChildren = {
  AuthTeacherIndexRoute: AuthTeacherIndexRoute,
}

const AuthTeacherRouteRouteWithChildren =
  AuthTeacherRouteRoute._addFileChildren(AuthTeacherRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthAdminRouteRoute: typeof AuthAdminRouteRouteWithChildren
  AuthLearnRouteRoute: typeof AuthLearnRouteRouteWithChildren
  AuthTeacherRouteRoute: typeof AuthTeacherRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAdminRouteRoute: AuthAdminRouteRouteWithChildren,
  AuthLearnRouteRoute: AuthLearnRouteRouteWithChildren,
  AuthTeacherRouteRoute: AuthTeacherRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
