/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ProtectedTeacherRouteRouteImport } from './routes/_protected/teacher/route'
import { Route as ProtectedLearnRouteRouteImport } from './routes/_protected/learn/route'
import { Route as ProtectedAdminRouteRouteImport } from './routes/_protected/admin/route'
import { Route as ProtectedTeacherIndexRouteImport } from './routes/_protected/teacher/index'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected/admin/index'
import { Route as ProtectedLearnSelectTaskRouteImport } from './routes/_protected/learn/select-task'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTeacherRouteRoute = ProtectedTeacherRouteRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedLearnRouteRoute = ProtectedLearnRouteRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAdminRouteRoute = ProtectedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedTeacherIndexRoute = ProtectedTeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedTeacherRouteRoute,
} as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const ProtectedLearnSelectTaskRoute =
  ProtectedLearnSelectTaskRouteImport.update({
    id: '/select-task',
    path: '/select-task',
    getParentRoute: () => ProtectedLearnRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/learn': typeof ProtectedLearnRouteRouteWithChildren
  '/teacher': typeof ProtectedTeacherRouteRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/learn/select-task': typeof ProtectedLearnSelectTaskRoute
  '/admin/': typeof ProtectedAdminIndexRoute
  '/teacher/': typeof ProtectedTeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learn': typeof ProtectedLearnRouteRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/learn/select-task': typeof ProtectedLearnSelectTaskRoute
  '/admin': typeof ProtectedAdminIndexRoute
  '/teacher': typeof ProtectedTeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/_protected/learn': typeof ProtectedLearnRouteRouteWithChildren
  '/_protected/teacher': typeof ProtectedTeacherRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/_protected/learn/select-task': typeof ProtectedLearnSelectTaskRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
  '/_protected/teacher/': typeof ProtectedTeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/learn'
    | '/teacher'
    | '/login'
    | '/learn/select-task'
    | '/admin/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/learn' | '/login' | '/learn/select-task' | '/admin' | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/admin'
    | '/_protected/learn'
    | '/_protected/teacher'
    | '/login/'
    | '/_protected/learn/select-task'
    | '/_protected/admin/'
    | '/_protected/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/teacher': {
      id: '/_protected/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof ProtectedTeacherRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/learn': {
      id: '/_protected/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof ProtectedLearnRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/teacher/': {
      id: '/_protected/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof ProtectedTeacherIndexRouteImport
      parentRoute: typeof ProtectedTeacherRouteRoute
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/learn/select-task': {
      id: '/_protected/learn/select-task'
      path: '/select-task'
      fullPath: '/learn/select-task'
      preLoaderRoute: typeof ProtectedLearnSelectTaskRouteImport
      parentRoute: typeof ProtectedLearnRouteRoute
    }
  }
}

interface ProtectedAdminRouteRouteChildren {
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
}

const ProtectedAdminRouteRouteChildren: ProtectedAdminRouteRouteChildren = {
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
}

const ProtectedAdminRouteRouteWithChildren =
  ProtectedAdminRouteRoute._addFileChildren(ProtectedAdminRouteRouteChildren)

interface ProtectedLearnRouteRouteChildren {
  ProtectedLearnSelectTaskRoute: typeof ProtectedLearnSelectTaskRoute
}

const ProtectedLearnRouteRouteChildren: ProtectedLearnRouteRouteChildren = {
  ProtectedLearnSelectTaskRoute: ProtectedLearnSelectTaskRoute,
}

const ProtectedLearnRouteRouteWithChildren =
  ProtectedLearnRouteRoute._addFileChildren(ProtectedLearnRouteRouteChildren)

interface ProtectedTeacherRouteRouteChildren {
  ProtectedTeacherIndexRoute: typeof ProtectedTeacherIndexRoute
}

const ProtectedTeacherRouteRouteChildren: ProtectedTeacherRouteRouteChildren = {
  ProtectedTeacherIndexRoute: ProtectedTeacherIndexRoute,
}

const ProtectedTeacherRouteRouteWithChildren =
  ProtectedTeacherRouteRoute._addFileChildren(
    ProtectedTeacherRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedAdminRouteRoute: typeof ProtectedAdminRouteRouteWithChildren
  ProtectedLearnRouteRoute: typeof ProtectedLearnRouteRouteWithChildren
  ProtectedTeacherRouteRoute: typeof ProtectedTeacherRouteRouteWithChildren
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAdminRouteRoute: ProtectedAdminRouteRouteWithChildren,
  ProtectedLearnRouteRoute: ProtectedLearnRouteRouteWithChildren,
  ProtectedTeacherRouteRoute: ProtectedTeacherRouteRouteWithChildren,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
